CREATE DATABASE IF NOT EXISTS ask
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'box'@'localhost' IDENTIFIED BY PASSWORD 'django12345';

GRANT ALL PRIVILEGES ON ask.* TO 'box'@'localhost';
FLUSH PRIVILEGES;



